// Builds public/sitemap.xml and public/robots.txt for the combined site.
//
// The sitemap merges this site's own marketing pages with the SEO directory
// sitemap generated by the rig-ads-website repo (public/sitemap.xml on its
// seo-directory branch). Both sites serve under https://www.bigrig.app.
//
// Run after either site's pages change, then commit the outputs:
//   npm run build:sitemap
//
// The rig-ads repo is located as a sibling directory by default; override with
//   RIG_ADS_DIR=/path/to/rig-ads-website npm run build:sitemap
import fs from 'fs'
import path from 'path'
import url from 'url'

const __dirname = path.dirname(url.fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..')
const PUBLIC_DIR = path.join(ROOT, 'public')
// Canonical host is the apex (www 301s back to it).
const ORIGIN = 'https://bigrig.app'

const RIG_ADS_DIR = process.env.RIG_ADS_DIR || path.join(ROOT, '..', 'rig-ads-website')

// --- This site's own pages ---------------------------------------------------
const ownUrls = [
  { loc: `${ORIGIN}/`, priority: '1.0' },
  { loc: `${ORIGIN}/products/`, priority: '0.9' },
  { loc: `${ORIGIN}/owner-operators/`, priority: '0.9' },
  { loc: `${ORIGIN}/shops/`, priority: '0.9' },
]

// --- Directory sitemap from the rig-ads-website repo -------------------------
const adsSitemapPath = path.join(RIG_ADS_DIR, 'public', 'sitemap.xml')
let adsUrls = []
if (fs.existsSync(adsSitemapPath)) {
  const xml = fs.readFileSync(adsSitemapPath, 'utf8')
  // States the directory's coverage gate excludes (their pages 404 in prod).
  // The rig-ads sitemap generator doesn't apply the gate; filter here until it does.
  const UNCOVERED_STATES = ['ak', 'hi']
  const uncovered = new RegExp(`/semi-truck-repair/(${UNCOVERED_STATES.join('|')})/`)
  let dropped = 0
  for (const m of xml.matchAll(/<url>\s*<loc>([^<]+)<\/loc>(?:\s*<priority>([^<]+)<\/priority>)?\s*<\/url>/g)) {
    if (uncovered.test(m[1])) {
      dropped++
      continue
    }
    // The rig-ads repo still emits www URLs; canonicalize to the apex.
    adsUrls.push({ loc: m[1].replace('https://www.bigrig.app', ORIGIN), priority: m[2] || '0.5' })
  }
  if (dropped) console.log(`dropped ${dropped} URLs for uncovered states (${UNCOVERED_STATES.join(', ')})`)
  console.log(`merged ${adsUrls.length} URLs from ${adsSitemapPath}`)
} else {
  console.warn(`WARNING: ${adsSitemapPath} not found — sitemap will only contain this site's pages.`)
  console.warn('Check out the rig-ads-website repo next to this one (seo-directory branch), or set RIG_ADS_DIR.')
}

// Own pages win on duplicate locs (e.g. both repos claiming "/").
const seen = new Set()
const urls = []
for (const u of [...ownUrls, ...adsUrls]) {
  if (seen.has(u.loc)) continue
  seen.add(u.loc)
  urls.push(u)
}

const sitemapXml =
  '<?xml version="1.0" encoding="UTF-8"?>\n' +
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
  urls.map((u) => `  <url><loc>${u.loc}</loc><priority>${u.priority}</priority></url>`).join('\n') +
  '\n</urlset>\n'

fs.writeFileSync(path.join(PUBLIC_DIR, 'sitemap.xml'), sitemapXml)
console.log(`sitemap.xml: ${urls.length} URLs`)

// --- robots.txt ---------------------------------------------------------------
// If the rig-ads repo ships its own robots rules, carry them over (minus any
// Sitemap lines — the merged sitemap below is the single source).
const adsRobotsPath = path.join(RIG_ADS_DIR, 'public', 'robots.txt')
let rules = 'User-agent: *\nAllow: /\n'
if (fs.existsSync(adsRobotsPath)) {
  const adsRules = fs
    .readFileSync(adsRobotsPath, 'utf8')
    .split('\n')
    .filter((line) => !/^sitemap:/i.test(line.trim()))
    .join('\n')
    .trim()
  if (adsRules) rules = adsRules + '\n'
  console.log(`merged robots rules from ${adsRobotsPath}`)
}

fs.writeFileSync(path.join(PUBLIC_DIR, 'robots.txt'), `${rules}\nSitemap: ${ORIGIN}/sitemap.xml\n`)
console.log('robots.txt written')
